### ISSUE TITLE
`git hub` does not show help on mac

### ISSUE THREAD

**Issue by jenspinney** [ingydotnet/git-hub#186] opened 2015-09-04 01:00 UTC

**Comment by raimue** [comment] 2016-11-10 18:22
Cannot reproduce. Without more details I would assume this was just an installation issue.

**Comment by jenspinney** [comment] 2016-11-10 21:55
@ingydotnet made this issue from my account (while pairing). I blame him for the lack of details :P 

This was also a while ago, so maybe something changed and it works now.

**Comment by perlpunk** [comment] 2016-11-11 14:48
@jenspinney ok thanks, then I'll close this for now.

**Closed by perlpunk** 2016-11-11 14:48 UTC
Labels: bug
